title: Modified federation settings
id: 
status: experimental
description: Detects changes to federation changes in AzureAD
references:
    - https://techcommunity.microsoft.com/t5/azure-active-directory-identity/azure-ad-workbook-to-help-you-assess-solorigate-risk/ba-p/2010718
	- https://docs.microsoft.com/en-us/azure/active-directory/hybrid/whatis-fed
    - https://attack.mitre.org/techniques/T1078/
tags:
    - attack.Valid accounts
    - attack.T1078
author: '@NoLogsNoCrime'
date: 2020/12/23
modified: 
logsource:
    product: Cloud
    service: Azure
detection:
    selection:
        AzureActiveDirectory
        Message|contains:
            - 'DirectoryManagement'
    condition: selection
fields:
    - Operation
    - TargetID
    - ActorID
falsepositives:
    - Updating legitimate properties to existing federation information or features. Any actions which modify or add domain federation trusts are rare and should be treated as high fidelity to be investigated as soon as possible.
level: medium